<div class="centered">
  <h1>Your contact list</h1>
  <?php if (empty($contacts)): ?>
  <p>
    You have no contact.
  </p>
  <?php else: ?>
  <div id="contact-list">
    <?php foreach ($contacts as $contact): ?>
    <div>
      <?php echo $this->contact($contact); ?>
      <div class="actions">
        <a href="#">Open</a>
        <ul>
          <li><a class="delete" href="<?php echo $this->url('contact/remove/' . $contact->getId()); ?>"/>Remove</a></li>
        </ul>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
  <?php endif; ?>
  <hr class="clear"/>
  <p>
    Give people this link:
    <a href="<?php echo $this->url('contact/request/' . $account->getId()); ?>">
      <?php echo $this->url('contact/request/' . $account->getId()); ?>
    </a>
    so they can add you to their contact list (right click and copy it to get the full URL).
  </p>
  </div>