<div id="login" class="centered">
  <h1>Please login</h1>
  <form action="<?php echo $url; ?>" method="post">
    <div>
      <input type="text" name="username" placeholder="Username"/><br/>
      <input type="password" name="password" placeholder="Password"/>
      <ul class="options clear">
        <li><a href="<?php echo $this->url('account/password/request'); ?>">Forgotten password?</a></li>
      </ul>
    </div>
    <div class="actions">
      <input type="submit" value="Login">
    </div>
  </form>
</div>