<div id="login" class="centered">
  <h1>Password change</h1>
  <form action="<?php echo $url; ?>" method="post">
    <div>
      <input type="password" name="password_current" placeholder="Current password"/>
      <br/>
      <input type="password" name="password_new" placeholder="New password"/>
      <br/>
      <input type="password" name="password_confirm" placeholder="Confirmation"/>
    </div>
    <div class="actions">
      <input type="submit" value="Change">
    </div>
  </form>
</div>