<div id="login" class="centered">
  <h1>Change your password</h1>
  <form action="<?php echo $url; ?>" method="post">
    <div>
      <input type="password" name="password_current" placeholder="Current password"/>
      <br/>
      <input type="password" name="password_new" placeholder="New password"/>
      <br/>
      <input type="password" name="password_confirm" placeholder="Confirmation"/>
      <ul class="options clear">
        <li><a href="<?php echo $this->url('account/password/request'); ?>">Current password forgotten?</a></li>
      </ul>
    </div>
    <div class="actions">
      <input type="submit" value="Change">
    </div>
  </form>
</div>