<div id="login" class="centered-form">
  <h1>Forgotten credentials?</h1>
  <form action="<?php echo $url; ?>" method="post">
    <div>
      <input type="text" name="mail" placeholder="Your mail address"/>
      <br/>
      <input type="text" name="mail_confirm" placeholder="Re-type you mail address"/>
    </div>
    <div class="actions">
      <input type="submit" value="Request new password">
    </div>
  </form>
</div>