<h1>Preferences</h1>
<form  action="<?php echo $url; ?>" method="POST" id="settings">

  <!-- Identity settings -->
  <fieldset>
    <legend>Identity</legend>
    <div class="field">
      <label for="to">Login</label>
      <div class="control">
        <input disabled="disabled" type="text" name="login" value="<?php echo $account->getUsername(); ?>"/>
      </div>
    </div>
    <div class="field">
      <label for="displayName">Full name</label>
      <div class="control">
        <input
          type="text"
          name="displayName"
          placeholder="<?php echo $placeholders['displayName']; ?>"
          value="<?php echo $defaults['displayName']; ?>"
        />
      </div>
    </div>
    <div class="field">
      <label for="organization">Organization</label>
      <div class="control">
        <input
          type="text"
          name="organization"
          placeholder="<?php echo $placeholders['organization']; ?>"
          value="<?php echo $defaults['organization']; ?>"
        />
      </div>
    </div>
    <div class="field">
      <label for="mail">Your email address</label>
      <div class="control">
        <input
          type="text"
          name="mail"
          placeholder="<?php echo $placeholders['mail']; ?>"
          value="<?php echo $defaults['mail']; ?>"
        />
      </div>
    </div>
    <div class="field">
      <label for="replyTo">Reply-to address</label>
      <div class="control">
        <input
          type="text"
          name="replyTo"
          placeholder="<?php echo $placeholders['replyTo']; ?>"
          value="<?php echo $defaults['replyTo']; ?>"
        />
      </div>
    </div>
  </fieldset>

  <!-- Compose settings -->
  <fieldset>
    <legend>Compose</legend>
    <div class="field">
      <label for="to">Copy sent mails to</label>
      <div class="control">
        <select name="login">
          <option value="inbox">Inbox</option>
          <option value="sent">Sent mail folder</option>
          <option value="">Nowhere</option>
        </select>
      </div>
    </div>
  </fieldset>

  <div class="field">
    <div class="control">
      <div class="actions">
        <input type="submit" value="Save"/>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</form>