<div id="actions">
  <ul class="nav-left">
    <li>
      <a href="<?php echo $this->url('app/albums'); ?>">
        Albums
      </a>
    </li>
    <li>
      <a href="<?php echo $this->url('app/albums/' . $album->getId()); ?>">
        <?php echo $album->getDisplayName(); ?>
      </a>
    </li>
  </ul>
</div>
<div class="centered-form">
  <form  action="<?php echo $url; ?>" method="POST">

    <fieldset>
      <legend>Share this album</legend>
      <div class="field">
        <label>Access level</label>
        <div class="control">
          <?php foreach ($accessLevel as $access => $label): ?>
          <input
            type="radio"
            name="accessLevel"
            value="<?php echo $label; ?>"
            <?php if ($access === $currentAccess): echo "checked=\"checked\""; endif; ?>
          />
          <?php echo $this->esc($label, true); ?><br/>
          <?php endforeach; ?>
        </div>
      </div>
      <div class="field">
        <label for="contacts">Share to contacts</label>
        <div class="control">
          <?php foreach ($contacts as $id => $name): ?>
          <input
            type="checkbox"
            name="contacts[<?php echo $id; ?>]"
            value="1"
            <?php if (in_array($id, $currentContacts)): echo "selected=\"selected\""; endif; ?>
          />
          <?php echo $this->esc($name, true); ?><br/>
          <?php endforeach; ?>
        </div>
      </div>
    </fieldset>

    <div class="field">
      <div class="control">
        <div class="actions">
          <input type="submit" value="Save"/>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </form>
</div>