<div id="actions">
  <ul class="nav-left">
    <li>
      <a href="<?php echo $this->url('app/albums'); ?>">
        Albums
      </a>
    </li>
    <li>
      <a href="<?php echo $this->url('app/albums/' . $album->getId()); ?>">
        <?php echo $album->getDisplayName(); ?>
      </a>
    </li>
  </ul>
</div>
<div class="centered-form">
  <form  action="<?php echo $url; ?>" method="POST">

    <fieldset>
      <legend>Share to</legend>
      <div class="field">
        <label for="userName">Display name</label>
        <div class="control">
          <input type="text" name="userName" value="<?php echo $album->getDisplayName(); ?>"/>
        </div>
      </div>
      <!--
       @todo User date
       @todo Permissions
       -->
    </fieldset>

    <div class="field">
      <div class="control">
        <div class="actions">
          <input type="submit" value="Save"/>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </form>
</div>