<div id="actions">
  <span class="nav-left">
    <a href="<?php echo $this->url('app/albums'); ?>">
      &laquo;&nbsp;Go back
    </a>
  </span>
  <ul class="nav-right">
    <li>
      <a href="#">Share</a>
    </li>
    <li>
      <a href="<?php echo $this->url('app/albums/' . $album->getId() . '/edit'); ?>">Edit</a>
    </li>
  </ul>
</div>
<div id="albums" class="centered">
  <h1>
    <?php echo $this->esc($owner->getDisplayName(), true); ?>
    /
    <?php echo $this->esc($album->getDisplayName(), true); ?>
  </h1>
  <!-- 
  <div class="centered">
    Display as:
    <a href="<?php echo $this->url('albums/' . $album->getId(), array('size' => 'thumbnail')); ?>">small</a>
    or <a href="<?php echo $this->url('albums/' . $album->getId()); ?>">normal</a>
  </div>
   -->
  <div class="medias">
    <?php echo $this->mediaGrid($medias, 4, 300, true, 'w600'); ?>
  </div>
  <?php echo $this->pager($pager); ?>
</div>