<div id="actions">
  <ul class="nav-left">
    <li>
      <a href="<?php echo $this->url('app/albums'); ?>">
        Albums
      </a>
    </li>
  </ul>
  <ul class="nav-right">
    <li>
      <a href="<?php echo $this->url('app/albums/' . $album->getId() . '/share'); ?>">Share</a>
    </li>
    <li>
      <a href="<?php echo $this->url('app/albums/' . $album->getId() . '/edit'); ?>">Edit</a>
    </li>
  </ul>
</div>
<div id="album" class="centered">
  <h1>
    <?php echo $this->esc($album->getDisplayName(), true); ?>
  </h1>
  <p class="user-date">
    <?php echo $this->dateRange($album->getUserBeginDate(), $album->getUserEndDate(), 'd/m/Y H:i'); ?>
  </p>
  <!-- 
  <div class="centered">
    Display as:
    <a href="<?php echo $this->url('albums/' . $album->getId(), array('size' => 'thumbnail')); ?>">small</a>
    or <a href="<?php echo $this->url('albums/' . $album->getId()); ?>">normal</a>
  </div>
   -->
  <hr/>
  <div class="medias">
    <?php echo $this->mediaGrid($medias, 4, 300, true, 600); ?>
  </div>
  <?php echo $this->pager($pager); ?>
</div>