<div id="actions">
  <span class="nav-left">
    <a href="<?php echo $this->url('app/import'); ?>">
      &laquo;&nbsp;Go back
    </a>
  </span>
</div>
<div class="centered">
  <h1>Select folders to import</h1>
  <form  action="<?php echo $url; ?>" method="POST" id="settings">

    <fieldset>
      <legend>Files</legend>
      <div class="field">
        <label for="directories">Select albums</label>
        <?php foreach ($directories as $index => $directory): ?>
        <div class="control">
          <input type="checkbox" name="directories[<?php echo $index; ?>]" value="<?php echo $directory['path']; ?>"/>
          <?php echo $this->esc($directory['label'], true); ?>
          <br/>
        </div>
        <?php endforeach; ?>
      </div>
    </fieldset>

    <div class="field">
      <div class="control">
        <div class="actions">
          <input type="submit" value="Import"/>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </form>
</div>