<div id="actions">
  <ul class="nav-left">
    <li>
      <a href="<?php echo $this->url('share/album'); ?>">
        Shared albums
      </a>
    </li>
  </ul>
</div>
<div id="login" class="centered">
  <h1>Password required</h1>
  <form action="<?php echo $url; ?>" method="post">
    <div>
      <input type="password" name="password" placeholder="Password"/>
    </div>
    <div class="actions">
      <input type="submit" value="Continue">
    </div>
  </form>
</div>