<div id="actions">
  <ul class="nav-left">
    <li>
      <a href="<?php echo $this->url('app/timeline'); ?>">
        Timeline
      </a>
    </li>
  </ul>
  <ul class="nav-right">
    <li>
      <a href="<?php echo $this->url('app/import'); ?>">+&nbsp;Add</a>
    </li>
  </ul>
</div>
<div id="albums" class="centered">
  <h1>Albums</h1>
  <?php foreach ($albums as $album): ?>
  <div class="album">
    <a href="<?php echo $this->url('app/albums/' . $album->getId()); ?>">
      <?php if (isset($previews[$album->getId()])): ?>
      <?php echo $this->media($previews[$album->getId()], '200', false); ?><br/>
      <?php endif; ?>
      <?php echo $this->esc($album->getDisplayName(), true); ?>
    </a>
  </div>
  <?php endforeach; ?>
</div>