<div id="albums">
  <h1>
    <?php echo $this->esc($owner->getDisplayName(), true); ?>
    /
    <?php echo $this->esc($album->getDisplayName(), true); ?>
  </h1>
  <!-- 
  <div class="centered">
    Display as:
    <a href="<?php echo $this->url('albums/' . $album->getId(), array('size' => 'thumbnail')); ?>">small</a>
    or <a href="<?php echo $this->url('albums/' . $album->getId()); ?>">normal</a>
  </div>
   -->
  <div class="medias">
  <?php foreach ($medias as $media): ?>
    <div class="media">
    <?php echo $this->media($media, '200', true); ?><br/>
    <?php echo $this->esc($media->getDisplayName(), true); ?>
    </div>
  <?php endforeach; ?>
  </div>
  <?php echo $this->pager($query); ?>
</div>