<div id="albums">
  <h1>Albums</h1>
  <?php foreach ($albums as $album): ?>
  <div class="album">
    <a href="<?php echo $this->url('app/albums/' . $album->getId()); ?>">
      <?php if (isset($previews[$album->getId()])): ?>
      <?php echo $this->media($previews[$album->getId()], '200', false); ?><br/>
      <?php endif; ?>
      <?php echo $album->getDisplayName(); ?>
    </a>
  </div>
  <?php endforeach; ?>
</div>