<div id="actions">
  <span class="nav-left">
    <a href="<?php echo $this->url('app/albums/' . $album->getId()); ?>">
      &laquo;&nbsp;Go back
    </a>
  </span>
  <ul class="nav-right">
    <li>
      <a href="#">Share</a>
    </li>
    <li>
      <a href="<?php echo $this->url('app/media/' . $media->getId() . '/edit'); ?>">Edit</a>
    </li>
  </ul>
</div>
<div id="media" class="centered">
  <h1>
    <?php echo $owner->getDisplayName(); ?>
    /
    <a href="<?php echo $this->url('app/albums/' . $album->getId()); ?>">
      <?php echo $this->esc($album->getDisplayName(), true); ?>
    </a>
    /
    <?php echo $this->esc($media->getDisplayName(), true); ?>
  </h1>
  <?php if ($prev): ?>
  <div class="media-prev">
    <a href="<?php echo $this->url('app/media/' . $prev->getId()); ?>">Previous</a>
  </div>
  <?php endif; ?>
  <div class="media">
    <?php echo $this->media($media, $size, true, 'full'); ?>
  </div>
  <?php if ($next): ?>
  <div class="media-next">
    <a href="<?php echo $this->url('app/media/' . $next->getId()); ?>">Next</a>
  </div>
  <?php endif; ?>
</div>