<?php if (!$isAuthenticated && $canRegister): ?>
<div id="actions">
  <ul class="nav-right">
    <li>
      <a href="<?php echo $this->url('share/account'); ?>">Create an account</a>
    </li>
  </ul>
</div>
<?php endif; ?>
<div id="albums" class="centered">
  <h1>Your shared albums</h1>
  <?php foreach ($albums as $album): ?>
  <?php if ($album->isShared() && $album->getSharePassword()): ?>
  <div class="album shared password">
  <?php elseif ($album->isShared()): ?>
  <div class="album shared">
  <?php else: ?>
  <div class="album">
  <?php endif; ?>
    <a href="<?php echo $this->url('share/album/' . $album->getShareToken()); ?>">
      <?php if (isset($previews[$album->getId()])): ?>
      <?php echo $this->media($previews[$album->getId()], 's200', false); ?><br/>
      <?php endif; ?>
      <?php echo $this->esc($album->getDisplayName(), true); ?>
    </a>
  </div>
  <?php endforeach; ?>
</div>