<div class="centered">
  <h1>Account services</h1>
  <ul class="menu">
    <li>
      <a href="<?php echo $this->url("account/settings"); ?>">Account settings</a>
      <br/>
      Configure your account informations.
    </li>
    <li>
      <a href="<?php echo $this->url("account/password"); ?>">Change my password</a>
      <br/>
      Change or request a new password.
    </li>
    <li>
      <a href="<?php echo $this->url("account/logout"); ?>">Logout</a>
    </li>
  </ul>
</div>