<!DOCTYPE html>
<html>
<head>
<title><?php if ($pagetitle): echo $pagetitle . ' | '; endif; ?><?php echo $title; ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="<?php echo $this->url("asset/css/normalize.css"); ?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->url("asset/css/common.css"); ?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->url("asset/css/skin.css"); ?>" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->url("asset/js/jquery-2.0.3.min.js"); ?>"></script>
</head>
<body>
<nav id="nav" role="navigation">
  <span class="brand nav-left">
    <a href="<?php echo $this->url($index); ?>"><?php echo $title; ?></a>
  </span>
  <ul class="nav-right">
    <?php if ($isAuthenticated): ?>
    <li><a href="<?php echo $this->url("contact/list"); ?>">Contacts</a></li>
    <li><a href="<?php echo $this->url("account"); ?>">Account</a></li>
    <li><a href="<?php echo $this->url("app/settings"); ?>">Preferences</a></li>
    <li><a href="<?php echo $this->url("account/logout"); ?>">Logout</a></li>
    <?php endif; ?>
  </ul>
</nav>
<div id="main">
<div id="messages" role="alertdialog">
<!-- <a href="#" class="close">Close</a> -->
<ul>
<?php foreach ($this->messages() as $message): ?>
<li role="alert" class="<?php echo $message->getTypeString(); ?>">
<?php echo $this->esc($message->getMessage()); ?>
</li>
<?php endforeach; ?>
</ul>
</div>
<?php echo $content; ?>
</div>
<script type="text/javascript" src="<?php echo $this->url("asset/js/main.js"); ?>" defer></script>
<script type="text/javascript" src="<?php echo $this->url("asset/js/lazy.min.js"); ?>" async></script>
<script type="text/javascript" defer>
//<![CDATA[
(function (document, $) {
  "use strict";
  $(document).ready(function() {
    $("#messages").on("click", function () {
      $("#messages").slideUp();
    });
  });
}(document, jQuery));
//]]>
</script>
</body>
</html>